[package]
name = "ledger"
version = "0.1.0"
authors = ["d2ci8xc5 <d2ci8xc5@tuta.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shrust = "0.0.7" #Quick CLI command loop and registry 
chrono = "0.4" # Date/Time
